### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by asim** [embedscript/frontend#18]
- [ ] Use `<script src="https://embedscript.com/assets/script.js?project=helloworld"></script>" as the copy link
- [ ] Use "Helloworld" for the banner so it greets people and render (its blank right now)
- [ ] "Login to edit script" to "Edit" for the button
- [ ] Discover link and /discover to list all scripts like (https://gist.github.com/discover)
- [ ] Attempting to register fails with a 400 error for SendVerificationEmail endpoint (if already registered)
- [x] Add signup "recover" link so we can sent password reset email
- [ ] Send welcome / reset emails with an EmbedScript branded template
- [x] Logout button
- [ ] New Script button
